import type { TaskItem, TaskRiskLevel, TaskSlaStatus, TaskStatus } from './taskManagement.types';

export const mockTasks: TaskItem[] = [
  {
    name: '施工围挡与临时动线审批',
    code: 'PRJ-001-T-001',
    projectName: '上海南京路旗舰店',
    parentPath: '开店筹备 / 施工准备',
    status: '待分配',
    statusTone: 'neutral',
    owner: '待分配',
    plannedStartAt: '2026-04-06',
    plannedEndAt: '2026-04-08',
    slaStatus: '即将超时',
    slaTone: 'orange',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '无前置任务',
    remindCount: 2,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 0,
  },
  {
    name: '强弱电综合布线实施',
    code: 'PRJ-001-T-002',
    projectName: '上海南京路旗舰店',
    parentPath: '施工执行 / 水电工程',
    status: '执行中',
    statusTone: 'blue',
    owner: '王强',
    plannedStartAt: '2026-04-03',
    plannedEndAt: '2026-04-12',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置已完成',
    remindCount: 1,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 45,
  },
  {
    name: '消防喷淋系统联调并提交报告',
    code: 'PRJ-001-T-003',
    projectName: '上海南京路旗舰店',
    parentPath: '施工执行 / 消防工程',
    status: '待提交',
    statusTone: 'orange',
    owner: '赵敏',
    plannedStartAt: '2026-04-01',
    plannedEndAt: '2026-04-07',
    slaStatus: '超时',
    slaTone: 'red',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置已完成',
    remindCount: 4,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 88,
  },
  {
    name: '样板区验收问题整改复检',
    code: 'PRJ-001-T-004',
    projectName: '上海南京路旗舰店',
    parentPath: '质量验收 / 分区验收',
    status: '不通过',
    statusTone: 'red',
    owner: '李娜',
    plannedStartAt: '2026-04-02',
    plannedEndAt: '2026-04-06',
    slaStatus: '超时',
    slaTone: 'red',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置阻塞',
    remindCount: 3,
    standardBindingStatus: '未绑定',
    isBlocked: true,
    progress: 60,
  },
  {
    name: '门头招牌安装验收',
    code: 'PRJ-002-T-001',
    projectName: '杭州西湖银泰店',
    parentPath: '施工执行 / 外立面工程',
    status: '待验收',
    statusTone: 'neutral',
    owner: '张伟',
    plannedStartAt: '2026-04-04',
    plannedEndAt: '2026-04-09',
    slaStatus: '即将超时',
    slaTone: 'orange',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '前置已完成',
    remindCount: 2,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 95,
  },
  {
    name: '空调主机吊装及试运行',
    code: 'PRJ-002-T-002',
    projectName: '杭州西湖银泰店',
    parentPath: '施工执行 / 机电安装',
    status: '执行中',
    statusTone: 'blue',
    owner: '孙杰',
    plannedStartAt: '2026-04-05',
    plannedEndAt: '2026-04-15',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '前置进行中',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 30,
  },
  {
    name: '智能照明回路测试',
    code: 'PRJ-002-T-003',
    projectName: '杭州西湖银泰店',
    parentPath: '施工执行 / 电气工程',
    status: '待执行',
    statusTone: 'neutral',
    owner: '王强',
    plannedStartAt: '2026-04-10',
    plannedEndAt: '2026-04-13',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '低风险',
    riskTone: 'blue',
    predecessorStatus: '前置进行中',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 0,
  },
  {
    name: '收银区定制柜体安装',
    code: 'PRJ-003-T-001',
    projectName: '北京朝阳大悦城店',
    parentPath: '软装陈列 / 家具安装',
    status: '待创建',
    statusTone: 'neutral',
    owner: '待分配',
    plannedStartAt: '2026-04-14',
    plannedEndAt: '2026-04-20',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '低风险',
    riskTone: 'blue',
    predecessorStatus: '无前置任务',
    remindCount: 0,
    standardBindingStatus: '未绑定',
    isBlocked: false,
    progress: 0,
  },
  {
    name: '品牌VI墙面喷绘复核',
    code: 'PRJ-003-T-002',
    projectName: '北京朝阳大悦城店',
    parentPath: '软装陈列 / 品牌物料',
    status: '已完成',
    statusTone: 'green',
    owner: '李娜',
    plannedStartAt: '2026-03-28',
    plannedEndAt: '2026-04-02',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '低风险',
    riskTone: 'blue',
    predecessorStatus: '前置已完成',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 100,
  },
  {
    name: '全店安全巡检闭环',
    code: 'PRJ-003-T-003',
    projectName: '北京朝阳大悦城店',
    parentPath: '开业准备 / 安全合规',
    status: '已关闭',
    statusTone: 'green',
    owner: '张质检',
    plannedStartAt: '2026-03-26',
    plannedEndAt: '2026-03-30',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '前置已完成',
    remindCount: 1,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 100,
  },
  {
    name: '门店消防审批资料补正',
    code: 'PRJ-004-T-001',
    projectName: '深圳万象天地店',
    parentPath: '证照办理 / 消防审批',
    status: '待提交',
    statusTone: 'orange',
    owner: '赵敏',
    plannedStartAt: '2026-04-01',
    plannedEndAt: '2026-04-05',
    slaStatus: '超时',
    slaTone: 'red',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置已完成',
    remindCount: 5,
    standardBindingStatus: '未绑定',
    isBlocked: true,
    progress: 70,
  },
  {
    name: '试营业人员培训签到与考核',
    code: 'PRJ-004-T-002',
    projectName: '深圳万象天地店',
    parentPath: '开业准备 / 人员培训',
    status: '待验收',
    statusTone: 'neutral',
    owner: '孙杰',
    plannedStartAt: '2026-04-06',
    plannedEndAt: '2026-04-11',
    slaStatus: '即将超时',
    slaTone: 'orange',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '前置已完成',
    remindCount: 2,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 92,
  },
];

export const groupOptions = [
  { value: 'none', label: '不分组' },
  { value: 'project', label: '按项目' },
  { value: 'status', label: '按状态' },
  { value: 'owner', label: '按负责人' },
];

export const sortOptions = [
  { value: 'default', label: '默认排序' },
  { value: 'planned-end-asc', label: '计划结束时间升序' },
  { value: 'risk-desc', label: '风险等级从高到低' },
  { value: 'remind-desc', label: '催办次数从高到低' },
];

export const statusOptions: TaskStatus[] = ['待创建', '待分配', '待执行', '执行中', '待提交', '待验收', '不通过', '已完成', '已关闭'];
export const riskOptions: TaskRiskLevel[] = ['高风险', '中风险', '低风险'];
export const slaOptions: TaskSlaStatus[] = ['超时', '即将超时', '正常'];
