/**
 * 项目团队管理 mock 数据
 * 用于项目详情页 - 团队管理标签页
 */

import type {
  ProjectTeamMember,
  ProjectTeamStats,
  ProjectRole,
  CollaborationWorkflow,
} from './projectTeam.types'

/**
 * 团队统计数据
 */
export const mockTeamStats: ProjectTeamStats = {
  totalMembers: 12,
  onlineCount: 8,
  digitalCount: 3,
  roleCoverage: 85,
  collaborationScore: 92,
}

/**
 * 团队成员列表
 */
export const mockTeamMembers: ProjectTeamMember[] = [
  {
    id: 'tm-001',
    userId: 'u-001',
    name: '张伟',
    department: '技术部',
    title: '项目经理',
    email: 'zhangwei@example.com',
    phone: '138-0000-0001',
    skills: ['项目管理', '敏捷开发', '团队协作'],
    currentLoad: {
      projectCount: 2,
      taskCount: 15,
      workHours: 42,
    },
    roleAssignments: [
      { roleId: 'role-pm', roleLabel: '项目经理', permissions: ['view', 'edit', 'approve'] },
    ],
    source: 'human',
    availability: 'online',
    avatar: '/assets/avatars/user-1.svg',
  },
  {
    id: 'tm-002',
    userId: 'u-002',
    name: '李娜',
    department: '设计部',
    title: 'UI设计师',
    email: 'lina@example.com',
    phone: '138-0000-0002',
    skills: ['UI设计', '交互设计', 'Figma'],
    currentLoad: {
      projectCount: 3,
      taskCount: 8,
      workHours: 38,
    },
    roleAssignments: [
      { roleId: 'role-designer', roleLabel: '设计师', permissions: ['view', 'edit'] },
    ],
    source: 'human',
    availability: 'online',
    avatar: '/assets/avatars/user-2.svg',
  },
  {
    id: 'tm-003',
    userId: 'u-003',
    name: '王强',
    department: '技术部',
    title: '前端工程师',
    email: 'wangqiang@example.com',
    phone: '138-0000-0003',
    skills: ['React', 'TypeScript', '前端开发'],
    currentLoad: {
      projectCount: 2,
      taskCount: 12,
      workHours: 45,
    },
    roleAssignments: [
      { roleId: 'role-dev', roleLabel: '开发工程师', permissions: ['view', 'edit'] },
    ],
    source: 'human',
    availability: 'busy',
    avatar: '/assets/avatars/user-3.svg',
  },
  {
    id: 'tm-004',
    userId: 'u-004',
    name: '刘洋',
    department: '技术部',
    title: '后端工程师',
    email: 'liuyang@example.com',
    phone: '138-0000-0004',
    skills: ['Node.js', 'Python', '数据库'],
    currentLoad: {
      projectCount: 1,
      taskCount: 10,
      workHours: 40,
    },
    roleAssignments: [
      { roleId: 'role-dev', roleLabel: '开发工程师', permissions: ['view', 'edit'] },
    ],
    source: 'human',
    availability: 'online',
    avatar: '/assets/avatars/user-4.svg',
  },
  {
    id: 'tm-005',
    userId: 'u-005',
    name: '陈静',
    department: '产品部',
    title: '产品经理',
    email: 'chenjing@example.com',
    phone: '138-0000-0005',
    skills: ['需求分析', '用户研究', '产品规划'],
    currentLoad: {
      projectCount: 2,
      taskCount: 6,
      workHours: 35,
    },
    roleAssignments: [
      { roleId: 'role-product', roleLabel: '产品经理', permissions: ['view', 'edit', 'approve'] },
    ],
    source: 'human',
    availability: 'online',
    avatar: '/assets/avatars/user-5.svg',
  },
  {
    id: 'tm-006',
    userId: 'u-006',
    name: '赵敏',
    department: '测试部',
    title: '测试工程师',
    email: 'zhaomin@example.com',
    phone: '138-0000-0006',
    skills: ['自动化测试', '性能测试', '测试工具'],
    currentLoad: {
      projectCount: 2,
      taskCount: 9,
      workHours: 38,
    },
    roleAssignments: [
      { roleId: 'role-qa', roleLabel: '测试工程师', permissions: ['view', 'edit'] },
    ],
    source: 'human',
    availability: 'offline',
    avatar: '/assets/avatars/user-6.svg',
  },
  {
    id: 'tm-007',
    userId: 'digi-001',
    name: 'AI 助手',
    department: '数字员工',
    title: 'AI 智能助手',
    email: 'ai-assistant@system.com',
    phone: '-',
    skills: ['数据分析', '文档生成', '任务调度'],
    currentLoad: {
      projectCount: 5,
      taskCount: 28,
      workHours: 168,
    },
    roleAssignments: [{ roleId: 'role-ai', roleLabel: 'AI 助手', permissions: ['view', 'edit'] }],
    source: 'digital',
    availability: 'online',
    avatar: '/assets/avatars/ai-1.svg',
  },
  {
    id: 'tm-008',
    userId: 'digi-002',
    name: '自动化测试 Agent',
    department: '数字员工',
    title: '自动化测试专家',
    email: 'test-agent@system.com',
    phone: '-',
    skills: ['自动化测试', '回归测试', '性能监控'],
    currentLoad: {
      projectCount: 4,
      taskCount: 18,
      workHours: 168,
    },
    roleAssignments: [
      { roleId: 'role-qa', roleLabel: '测试工程师', permissions: ['view', 'edit'] },
    ],
    source: 'digital',
    availability: 'online',
    avatar: '/assets/avatars/ai-2.svg',
  },
  {
    id: 'tm-009',
    userId: 'digi-003',
    name: '代码审查 Agent',
    department: '数字员工',
    title: '代码质量专家',
    email: 'code-reviewer@system.com',
    phone: '-',
    skills: ['代码审查', '安全检查', '性能优化'],
    currentLoad: {
      projectCount: 3,
      taskCount: 22,
      workHours: 168,
    },
    roleAssignments: [{ roleId: 'role-dev', roleLabel: '开发工程师', permissions: ['view'] }],
    source: 'digital',
    availability: 'busy',
    avatar: '/assets/avatars/ai-3.svg',
  },
  {
    id: 'tm-010',
    userId: 'u-007',
    name: '孙浩',
    department: '运维部',
    title: '运维工程师',
    email: 'sunhao@example.com',
    phone: '138-0000-0007',
    skills: ['服务器管理', 'Docker', 'CI/CD'],
    currentLoad: {
      projectCount: 3,
      taskCount: 7,
      workHours: 40,
    },
    roleAssignments: [
      { roleId: 'role-ops', roleLabel: '运维工程师', permissions: ['view', 'edit'] },
    ],
    source: 'human',
    availability: 'online',
    avatar: '/assets/avatars/user-7.svg',
  },
  {
    id: 'tm-011',
    userId: 'u-008',
    name: '周婷',
    department: '设计部',
    title: '视觉设计师',
    email: 'zhouting@example.com',
    phone: '138-0000-0008',
    skills: ['视觉设计', '品牌设计', '动效设计'],
    currentLoad: {
      projectCount: 2,
      taskCount: 5,
      workHours: 32,
    },
    roleAssignments: [
      { roleId: 'role-designer', roleLabel: '设计师', permissions: ['view', 'edit'] },
    ],
    source: 'human',
    availability: 'online',
    avatar: '/assets/avatars/user-8.svg',
  },
  {
    id: 'tm-012',
    userId: 'u-009',
    name: '吴磊',
    department: '技术部',
    title: '架构师',
    email: 'wulei@example.com',
    phone: '138-0000-0009',
    skills: ['系统架构', '技术选型', '性能优化'],
    currentLoad: {
      projectCount: 1,
      taskCount: 4,
      workHours: 28,
    },
    roleAssignments: [
      { roleId: 'role-architect', roleLabel: '架构师', permissions: ['view', 'edit', 'approve'] },
    ],
    source: 'human',
    availability: 'offline',
    avatar: '/assets/avatars/user-9.svg',
  },
]

/**
 * 项目角色定义
 */
export const mockProjectRoles: ProjectRole[] = [
  {
    id: 'role-pm',
    label: '项目经理',
    description: '负责项目整体规划、进度管理和团队协调',
    permissions: ['view', 'edit', 'approve'],
    memberCount: 1,
    color: '#3B82F6',
  },
  {
    id: 'role-product',
    label: '产品经理',
    description: '负责需求分析、产品规划和用户研究',
    permissions: ['view', 'edit', 'approve'],
    memberCount: 1,
    color: '#8B5CF6',
  },
  {
    id: 'role-designer',
    label: '设计师',
    description: '负责 UI 设计、交互设计和视觉设计',
    permissions: ['view', 'edit'],
    memberCount: 2,
    color: '#EC4899',
  },
  {
    id: 'role-dev',
    label: '开发工程师',
    description: '负责前端、后端开发和代码实现',
    permissions: ['view', 'edit'],
    memberCount: 4,
    color: '#10B981',
  },
  {
    id: 'role-qa',
    label: '测试工程师',
    description: '负责测试计划、测试执行和质量保证',
    permissions: ['view', 'edit'],
    memberCount: 2,
    color: '#F59E0B',
  },
  {
    id: 'role-ops',
    label: '运维工程师',
    description: '负责服务器管理、部署和运维支持',
    permissions: ['view', 'edit'],
    memberCount: 1,
    color: '#06B6D4',
  },
  {
    id: 'role-architect',
    label: '架构师',
    description: '负责系统架构设计和技术选型',
    permissions: ['view', 'edit', 'approve'],
    memberCount: 1,
    color: '#6366F1',
  },
  {
    id: 'role-ai',
    label: 'AI 助手',
    description: '提供智能化辅助支持，包括数据分析、文档生成等',
    permissions: ['view', 'edit'],
    memberCount: 3,
    color: '#14B8A6',
  },
]

/**
 * 协作流程列表
 */
export const mockCollaborationWorkflows: CollaborationWorkflow[] = [
  {
    id: 'wf-001',
    type: 'approval',
    name: '立项审批流程',
    description: '项目立项时触发的审批流程，需要项目经理和部门负责人审批',
    triggers: ['项目创建', '立项申请'],
    participants: ['项目经理', '部门负责人'],
    isActive: true,
  },
  {
    id: 'wf-002',
    type: 'approval',
    name: '变更审批流程',
    description: '项目范围、时间、成本变更时触发的审批流程',
    triggers: ['需求变更', '进度调整', '预算调整'],
    participants: ['项目经理', '产品经理', '部门负责人'],
    isActive: true,
  },
  {
    id: 'wf-003',
    type: 'approval',
    name: '验收审批流程',
    description: '里程碑验收时触发的审批流程',
    triggers: ['里程碑完成', '验收申请'],
    participants: ['项目经理', '产品经理', '客户'],
    isActive: true,
  },
  {
    id: 'wf-004',
    type: 'notification',
    name: '任务分配通知',
    description: '任务分配时自动发送通知给相关成员',
    triggers: ['任务创建', '任务分配', '任务转派'],
    participants: ['任务负责人', '项目经理'],
    isActive: true,
  },
  {
    id: 'wf-005',
    type: 'notification',
    name: '进度更新通知',
    description: '任务进度更新时自动发送通知',
    triggers: ['进度更新', '任务完成', '任务延期'],
    participants: ['项目经理', '团队成员'],
    isActive: true,
  },
  {
    id: 'wf-006',
    type: 'notification',
    name: '风险预警通知',
    description: '识别到风险时自动发送预警通知',
    triggers: ['风险识别', '风险升级', '问题上报'],
    participants: ['项目经理', '部门负责人'],
    isActive: true,
  },
  {
    id: 'wf-007',
    type: 'meeting',
    name: '项目例会',
    description: '每周定期召开的项目例会',
    triggers: ['每周一 10:00'],
    participants: ['项目团队全体成员'],
    isActive: true,
  },
  {
    id: 'wf-008',
    type: 'meeting',
    name: '里程碑评审会',
    description: '里程碑完成时召开的评审会议',
    triggers: ['里程碑完成'],
    participants: ['项目经理', '产品经理', '关键干系人'],
    isActive: true,
  },
]
