import Database from 'better-sqlite3'
import { join } from 'path'

const DB_PATH = join(import.meta.dirname, '..', 'local-api', 'store', 'prisma.db')
const db = new Database(DB_PATH)

const PROJECT_SHANGHAI = 'PRJ-001'
const PROJECT_HANGZHOU = 'PRJ-002'
const PROJECT_BEIJING = 'PRJ-003'
const PROJECT_SHENZHEN = 'PRJ-004'

interface SeedTask {
  id: string
  code: string
  name: string
  projectId: string
  projectName: string
  parentTaskId: string | null
  status: string
  statusTone: string
  owner: string
  assigneeId: string
  assigneeName: string
  nodeLevelType: string
  priority: string
  plannedStartAt: string
  plannedEndAt: string
  slaStatus: string
  slaTone: string
  riskLevel: string
  riskTone: string
  predecessorStatus: string
  remindCount: number
  standardBindingStatus: string
  isBlocked: boolean
  progress: number
  taskType: string
  sourceType: string
  tags: string[]
  createdBy: string
  createdAt: string
}

const mockProjects: Array<{ code: string; name: string }> = [
  { code: PROJECT_SHANGHAI, name: '上海南京路旗舰店' },
  { code: PROJECT_HANGZHOU, name: '杭州西湖银泰店' },
  { code: PROJECT_BEIJING, name: '北京朝阳大悦城店' },
  { code: PROJECT_SHENZHEN, name: '深圳万象天地店' },
]

const allMockTaskNodes: SeedTask[] = [
  // ── Work Packages ──
  {
    id: 'wp-sh-construction-prep',
    code: 'WP-SH-001',
    name: '施工准备',
    projectId: PROJECT_SHANGHAI,
    projectName: '上海南京路旗舰店',
    parentTaskId: PROJECT_SHANGHAI,
    status: '待分配',
    statusTone: 'neutral',
    owner: '项目经理',
    assigneeId: 'user-pm',
    assigneeName: '项目经理',
    nodeLevelType: 'work_package',
    priority: 'high',
    plannedStartAt: '2026-04-01',
    plannedEndAt: '2026-04-15',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '无前置任务',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 45,
    taskType: '里程碑',
    sourceType: 'template',
    tags: ['施工准备'],
    createdBy: '系统',
    createdAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'wp-sh-electrical',
    code: 'WP-SH-002',
    name: '水电工程',
    projectId: PROJECT_SHANGHAI,
    projectName: '上海南京路旗舰店',
    parentTaskId: PROJECT_SHANGHAI,
    status: '执行中',
    statusTone: 'blue',
    owner: '王强',
    assigneeId: 'user-wangqiang',
    assigneeName: '王强',
    nodeLevelType: 'work_package',
    priority: 'high',
    plannedStartAt: '2026-04-01',
    plannedEndAt: '2026-04-18',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置进行中',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 45,
    taskType: '关键任务',
    sourceType: 'template',
    tags: ['水电'],
    createdBy: '系统',
    createdAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'wp-sh-fire-safety',
    code: 'WP-SH-003',
    name: '消防安全',
    projectId: PROJECT_SHANGHAI,
    projectName: '上海南京路旗舰店',
    parentTaskId: PROJECT_SHANGHAI,
    status: '执行中',
    statusTone: 'blue',
    owner: '赵敏',
    assigneeId: 'user-zhaomin',
    assigneeName: '赵敏',
    nodeLevelType: 'work_package',
    priority: 'urgent',
    plannedStartAt: '2026-04-01',
    plannedEndAt: '2026-04-10',
    slaStatus: '即将超时',
    slaTone: 'orange',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置已完成',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 80,
    taskType: '关键任务',
    sourceType: 'template',
    tags: ['消防'],
    createdBy: '系统',
    createdAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'wp-sh-quality',
    code: 'WP-SH-004',
    name: '品质巡检',
    projectId: PROJECT_SHANGHAI,
    projectName: '上海南京路旗舰店',
    parentTaskId: PROJECT_SHANGHAI,
    status: '执行中',
    statusTone: 'blue',
    owner: '李娜',
    assigneeId: 'user-lina',
    assigneeName: '李娜',
    nodeLevelType: 'work_package',
    priority: 'high',
    plannedStartAt: '2026-04-02',
    plannedEndAt: '2026-04-12',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置进行中',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 50,
    taskType: '标准任务',
    sourceType: 'template',
    tags: ['品质'],
    createdBy: '系统',
    createdAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'wp-hz-exterior',
    code: 'WP-HZ-001',
    name: '外立面工程',
    projectId: PROJECT_HANGZHOU,
    projectName: '杭州西湖银泰店',
    parentTaskId: PROJECT_HANGZHOU,
    status: '执行中',
    statusTone: 'blue',
    owner: '张伟',
    assigneeId: 'user-zhangwei',
    assigneeName: '张伟',
    nodeLevelType: 'work_package',
    priority: 'medium',
    plannedStartAt: '2026-04-01',
    plannedEndAt: '2026-04-12',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '前置已完成',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 60,
    taskType: '标准任务',
    sourceType: 'template',
    tags: ['外立面'],
    createdBy: '系统',
    createdAt: '2026-03-22T08:00:00Z',
  },
  {
    id: 'wp-hz-mep',
    code: 'WP-HZ-002',
    name: '机电安装',
    projectId: PROJECT_HANGZHOU,
    projectName: '杭州西湖银泰店',
    parentTaskId: PROJECT_HANGZHOU,
    status: '执行中',
    statusTone: 'blue',
    owner: '孙杰',
    assigneeId: 'user-sunjie',
    assigneeName: '孙杰',
    nodeLevelType: 'work_package',
    priority: 'high',
    plannedStartAt: '2026-04-01',
    plannedEndAt: '2026-04-18',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '前置进行中',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 30,
    taskType: '里程碑',
    sourceType: 'template',
    tags: ['机电'],
    createdBy: '系统',
    createdAt: '2026-03-22T08:00:00Z',
  },
  {
    id: 'wp-hz-electrical',
    code: 'WP-HZ-003',
    name: '电气工程',
    projectId: PROJECT_HANGZHOU,
    projectName: '杭州西湖银泰店',
    parentTaskId: PROJECT_HANGZHOU,
    status: '待执行',
    statusTone: 'neutral',
    owner: '王强',
    assigneeId: 'user-wangqiang',
    assigneeName: '王强',
    nodeLevelType: 'work_package',
    priority: 'medium',
    plannedStartAt: '2026-04-08',
    plannedEndAt: '2026-04-15',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '低风险',
    riskTone: 'blue',
    predecessorStatus: '前置进行中',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 0,
    taskType: '关键任务',
    sourceType: 'template',
    tags: ['电气'],
    createdBy: '系统',
    createdAt: '2026-03-22T08:00:00Z',
  },
  {
    id: 'wp-bj-furniture',
    code: 'WP-BJ-001',
    name: '家具安装',
    projectId: PROJECT_BEIJING,
    projectName: '北京朝阳大悦城店',
    parentTaskId: PROJECT_BEIJING,
    status: '草稿',
    statusTone: 'neutral',
    owner: '待分配',
    assigneeId: '',
    assigneeName: '待分配',
    nodeLevelType: 'work_package',
    priority: 'low',
    plannedStartAt: '2026-04-10',
    plannedEndAt: '2026-04-22',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '低风险',
    riskTone: 'blue',
    predecessorStatus: '无前置任务',
    remindCount: 0,
    standardBindingStatus: '未绑定',
    isBlocked: false,
    progress: 0,
    taskType: '标准任务',
    sourceType: 'template',
    tags: ['家具'],
    createdBy: '系统',
    createdAt: '2026-03-28T08:00:00Z',
  },
  {
    id: 'wp-bj-branding',
    code: 'WP-BJ-002',
    name: '品牌物料',
    projectId: PROJECT_BEIJING,
    projectName: '北京朝阳大悦城店',
    parentTaskId: PROJECT_BEIJING,
    status: '已完成',
    statusTone: 'green',
    owner: '李娜',
    assigneeId: 'user-lina',
    assigneeName: '李娜',
    nodeLevelType: 'work_package',
    priority: 'medium',
    plannedStartAt: '2026-03-25',
    plannedEndAt: '2026-04-05',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '低风险',
    riskTone: 'blue',
    predecessorStatus: '前置已完成',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 100,
    taskType: '标准任务',
    sourceType: 'manual',
    tags: ['品牌'],
    createdBy: '系统',
    createdAt: '2026-03-25T08:00:00Z',
  },
  {
    id: 'wp-sz-permit',
    code: 'WP-SZ-001',
    name: '证照办理',
    projectId: PROJECT_SHENZHEN,
    projectName: '深圳万象天地店',
    parentTaskId: PROJECT_SHENZHEN,
    status: '待提交',
    statusTone: 'orange',
    owner: '赵敏',
    assigneeId: 'user-zhaomin',
    assigneeName: '赵敏',
    nodeLevelType: 'work_package',
    priority: 'urgent',
    plannedStartAt: '2026-04-01',
    plannedEndAt: '2026-04-08',
    slaStatus: '超时',
    slaTone: 'red',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置已完成',
    remindCount: 0,
    standardBindingStatus: '未绑定',
    isBlocked: true,
    progress: 70,
    taskType: '关键任务',
    sourceType: 'template',
    tags: ['证照'],
    createdBy: '系统',
    createdAt: '2026-03-25T08:00:00Z',
  },
  {
    id: 'wp-sz-training',
    code: 'WP-SZ-002',
    name: '人员培训',
    projectId: PROJECT_SHENZHEN,
    projectName: '深圳万象天地店',
    parentTaskId: PROJECT_SHENZHEN,
    status: '待验收',
    statusTone: 'neutral',
    owner: '孙杰',
    assigneeId: 'user-sunjie',
    assigneeName: '孙杰',
    nodeLevelType: 'work_package',
    priority: 'medium',
    plannedStartAt: '2026-04-03',
    plannedEndAt: '2026-04-14',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '前置已完成',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 92,
    taskType: '里程碑',
    sourceType: 'template',
    tags: ['培训'],
    createdBy: '系统',
    createdAt: '2026-03-25T08:00:00Z',
  },
  // ── Tasks ──
  {
    id: 'task-001',
    code: 'PRJ-001-T-001',
    name: '施工围挡与临时动线审批',
    projectId: PROJECT_SHANGHAI,
    projectName: '上海南京路旗舰店',
    parentTaskId: 'wp-sh-construction-prep',
    status: '待分配',
    statusTone: 'neutral',
    owner: '待分配',
    assigneeId: '',
    assigneeName: '待分配',
    nodeLevelType: 'task',
    priority: 'high',
    plannedStartAt: '2026-04-06',
    plannedEndAt: '2026-04-08',
    slaStatus: '即将超时',
    slaTone: 'orange',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '无前置任务',
    remindCount: 2,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 0,
    taskType: '标准任务',
    sourceType: 'template',
    tags: ['施工', '审批'],
    createdBy: '系统',
    createdAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'task-002',
    code: 'PRJ-001-T-002',
    name: '强弱电综合布线实施',
    projectId: PROJECT_SHANGHAI,
    projectName: '上海南京路旗舰店',
    parentTaskId: 'wp-sh-electrical',
    status: '执行中',
    statusTone: 'blue',
    owner: '王强',
    assigneeId: 'user-wangqiang',
    assigneeName: '王强',
    nodeLevelType: 'task',
    priority: 'urgent',
    plannedStartAt: '2026-04-03',
    plannedEndAt: '2026-04-12',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置已完成',
    remindCount: 1,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 45,
    taskType: '关键任务',
    sourceType: 'template',
    tags: ['电气', '施工'],
    createdBy: '系统',
    createdAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'task-003',
    code: 'PRJ-001-T-003',
    name: '消防喷淋系统联调并提交报告',
    projectId: PROJECT_SHANGHAI,
    projectName: '上海南京路旗舰店',
    parentTaskId: 'wp-sh-fire-safety',
    status: '待提交',
    statusTone: 'orange',
    owner: '赵敏',
    assigneeId: 'user-zhaomin',
    assigneeName: '赵敏',
    nodeLevelType: 'task',
    priority: 'urgent',
    plannedStartAt: '2026-04-01',
    plannedEndAt: '2026-04-07',
    slaStatus: '超时',
    slaTone: 'red',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置已完成',
    remindCount: 4,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 88,
    taskType: '关键任务',
    sourceType: 'template',
    tags: ['消防', '调试'],
    createdBy: '系统',
    createdAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'task-004',
    code: 'PRJ-001-T-004',
    name: '样板区验收问题整改复检',
    projectId: PROJECT_SHANGHAI,
    projectName: '上海南京路旗舰店',
    parentTaskId: 'wp-sh-quality',
    status: '不通过',
    statusTone: 'red',
    owner: '李娜',
    assigneeId: 'user-lina',
    assigneeName: '李娜',
    nodeLevelType: 'task',
    priority: 'high',
    plannedStartAt: '2026-04-02',
    plannedEndAt: '2026-04-06',
    slaStatus: '超时',
    slaTone: 'red',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置阻塞',
    remindCount: 3,
    standardBindingStatus: '未绑定',
    isBlocked: true,
    progress: 60,
    taskType: '标准任务',
    sourceType: 'manual',
    tags: ['验收', '整改'],
    createdBy: '李娜',
    createdAt: '2026-03-25T10:00:00Z',
  },
  {
    id: 'task-005',
    code: 'PRJ-002-T-001',
    name: '门头招牌安装验收',
    projectId: PROJECT_HANGZHOU,
    projectName: '杭州西湖银泰店',
    parentTaskId: 'wp-hz-exterior',
    status: '待验收',
    statusTone: 'neutral',
    owner: '张伟',
    assigneeId: 'user-zhangwei',
    assigneeName: '张伟',
    nodeLevelType: 'task',
    priority: 'medium',
    plannedStartAt: '2026-04-04',
    plannedEndAt: '2026-04-09',
    slaStatus: '即将超时',
    slaTone: 'orange',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '前置已完成',
    remindCount: 2,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 95,
    taskType: '标准任务',
    sourceType: 'template',
    tags: ['外立面', '验收'],
    createdBy: '系统',
    createdAt: '2026-03-22T08:00:00Z',
  },
  {
    id: 'task-006',
    code: 'PRJ-002-T-002',
    name: '空调主机吊装及试运行',
    projectId: PROJECT_HANGZHOU,
    projectName: '杭州西湖银泰店',
    parentTaskId: 'wp-hz-mep',
    status: '执行中',
    statusTone: 'blue',
    owner: '孙杰',
    assigneeId: 'user-sunjie',
    assigneeName: '孙杰',
    nodeLevelType: 'task',
    priority: 'high',
    plannedStartAt: '2026-04-05',
    plannedEndAt: '2026-04-15',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '前置进行中',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 30,
    taskType: '关键任务',
    sourceType: 'template',
    tags: ['机电', '安装'],
    createdBy: '系统',
    createdAt: '2026-03-22T08:00:00Z',
  },
  {
    id: 'task-007',
    code: 'PRJ-002-T-003',
    name: '智能照明回路测试',
    projectId: PROJECT_HANGZHOU,
    projectName: '杭州西湖银泰店',
    parentTaskId: 'wp-hz-electrical',
    status: '待执行',
    statusTone: 'neutral',
    owner: '王强',
    assigneeId: 'user-wangqiang',
    assigneeName: '王强',
    nodeLevelType: 'task',
    priority: 'low',
    plannedStartAt: '2026-04-10',
    plannedEndAt: '2026-04-13',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '低风险',
    riskTone: 'blue',
    predecessorStatus: '前置进行中',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 0,
    taskType: '标准任务',
    sourceType: 'template',
    tags: ['电气', '测试'],
    createdBy: '系统',
    createdAt: '2026-03-22T08:00:00Z',
  },
  {
    id: 'task-008',
    code: 'PRJ-003-T-001',
    name: '收银区定制柜体安装',
    projectId: PROJECT_BEIJING,
    projectName: '北京朝阳大悦城店',
    parentTaskId: 'wp-bj-furniture',
    status: '草稿',
    statusTone: 'neutral',
    owner: '待分配',
    assigneeId: '',
    assigneeName: '待分配',
    nodeLevelType: 'task',
    priority: 'low',
    plannedStartAt: '2026-04-14',
    plannedEndAt: '2026-04-20',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '低风险',
    riskTone: 'blue',
    predecessorStatus: '无前置任务',
    remindCount: 0,
    standardBindingStatus: '未绑定',
    isBlocked: false,
    progress: 0,
    taskType: '标准任务',
    sourceType: 'template',
    tags: ['家具', '安装'],
    createdBy: '系统',
    createdAt: '2026-03-28T08:00:00Z',
  },
  {
    id: 'task-009',
    code: 'PRJ-003-T-002',
    name: '品牌VI墙面喷绘复核',
    projectId: PROJECT_BEIJING,
    projectName: '北京朝阳大悦城店',
    parentTaskId: 'wp-bj-branding',
    status: '已完成',
    statusTone: 'green',
    owner: '李娜',
    assigneeId: 'user-lina',
    assigneeName: '李娜',
    nodeLevelType: 'task',
    priority: 'medium',
    plannedStartAt: '2026-03-28',
    plannedEndAt: '2026-04-02',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '低风险',
    riskTone: 'blue',
    predecessorStatus: '前置已完成',
    remindCount: 0,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 100,
    taskType: '标准任务',
    sourceType: 'manual',
    tags: ['VI', '复核'],
    createdBy: '李娜',
    createdAt: '2026-03-25T09:00:00Z',
  },
  {
    id: 'task-010',
    code: 'PRJ-003-T-003',
    name: '全店安全巡检闭环',
    projectId: PROJECT_BEIJING,
    projectName: '北京朝阳大悦城店',
    parentTaskId: null,
    status: '已关闭',
    statusTone: 'green',
    owner: '张质检',
    assigneeId: 'user-zhangzj',
    assigneeName: '张质检',
    nodeLevelType: 'task',
    priority: 'high',
    plannedStartAt: '2026-03-26',
    plannedEndAt: '2026-03-30',
    slaStatus: '正常',
    slaTone: 'green',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '前置已完成',
    remindCount: 1,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 100,
    taskType: '标准任务',
    sourceType: 'template',
    tags: ['安全', '巡检'],
    createdBy: '系统',
    createdAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'task-011',
    code: 'PRJ-004-T-001',
    name: '门店消防审批资料补正',
    projectId: PROJECT_SHENZHEN,
    projectName: '深圳万象天地店',
    parentTaskId: 'wp-sz-permit',
    status: '待提交',
    statusTone: 'orange',
    owner: '赵敏',
    assigneeId: 'user-zhaomin',
    assigneeName: '赵敏',
    nodeLevelType: 'task',
    priority: 'urgent',
    plannedStartAt: '2026-04-01',
    plannedEndAt: '2026-04-05',
    slaStatus: '超时',
    slaTone: 'red',
    riskLevel: '高风险',
    riskTone: 'red',
    predecessorStatus: '前置已完成',
    remindCount: 5,
    standardBindingStatus: '未绑定',
    isBlocked: true,
    progress: 70,
    taskType: '标准任务',
    sourceType: 'manual',
    tags: ['消防', '审批', '证照'],
    createdBy: '赵敏',
    createdAt: '2026-03-28T14:00:00Z',
  },
  {
    id: 'task-012',
    code: 'PRJ-004-T-002',
    name: '试营业人员培训签到与考核',
    projectId: PROJECT_SHENZHEN,
    projectName: '深圳万象天地店',
    parentTaskId: 'wp-sz-training',
    status: '待验收',
    statusTone: 'neutral',
    owner: '孙杰',
    assigneeId: 'user-sunjie',
    assigneeName: '孙杰',
    nodeLevelType: 'task',
    priority: 'medium',
    plannedStartAt: '2026-04-06',
    plannedEndAt: '2026-04-11',
    slaStatus: '即将超时',
    slaTone: 'orange',
    riskLevel: '中风险',
    riskTone: 'orange',
    predecessorStatus: '前置已完成',
    remindCount: 2,
    standardBindingStatus: '已绑定',
    isBlocked: false,
    progress: 92,
    taskType: '标准任务',
    sourceType: 'template',
    tags: ['培训', '考核'],
    createdBy: '系统',
    createdAt: '2026-03-25T08:00:00Z',
  },
]

console.log('[Seed] 开始写入种子数据...')

const projectInsert = db.prepare(`
  INSERT OR REPLACE INTO projects (
    code, name, brand, status, parent_status, sub_status_json,
    status_tone, stage, progress, budget, team_size, date_range,
    description, owner, risk_level, risk_count, milestone, tasks,
    planned_open_date, created_at, updated_at
  ) VALUES (
    @code, @name, @brand, @status, @parentStatus, @subStatusJson,
    @statusTone, @stage, @progress, @budget, @teamSize, @dateRange,
    @description, @owner, @riskLevel, @riskCount, @milestone, @tasks,
    @plannedOpenDate, @now, @now
  )
`)

const taskInsert = db.prepare(`
  INSERT OR REPLACE INTO project_tasks (
    project_id, code, name, status,
    assignee_id, assignee_name, start_date, due_date, parent_id, node_level_type,
    priority, progress, task_type, source_type, risk_level, sla_status, description,
    remind_count, tags, created_by, created_at, updated_at
  ) VALUES (
    @projectId, @code, @name, @status,
    @assigneeId, @assigneeName, @startDate, @dueDate, @parentId, @nodeLevelType,
    @priority, @progress, @taskType, @sourceType, @riskLevel, @slaStatus, @description,
    @remindCount, @tags, @createdBy, @now, @now
  )
`)

const now = new Date().toISOString()

// ── 1. 写入项目 ──
const projectCodeToDbId: Record<string, number> = {}
for (const p of mockProjects) {
  const result = projectInsert.run({
    code: p.code,
    name: p.name,
    brand: '标准品牌',
    status: '执行中',
    parentStatus: '执行',
    subStatusJson: null,
    statusTone: 'blue',
    stage: '执行',
    progress: 50,
    budget: null,
    teamSize: '15人',
    dateRange: '2026-04-01 ~ 2026-06-30',
    description: null,
    owner: null,
    riskLevel: null,
    riskCount: 0,
    milestone: null,
    tasks: null,
    plannedOpenDate: '2026-06-01',
    now,
  })
  projectCodeToDbId[p.code] = Number(result.lastInsertRowid)
  console.log(`[Seed] 项目: ${p.code} (id=${projectCodeToDbId[p.code]})`)
}

// ── 2. 写入任务（先设 parentId = null） ──
const frontendIdToDbId: Record<string, number> = {}
const parentMapping: Array<{ frontendId: string; dbId: number }> = []

for (const t of allMockTaskNodes) {
  const projectDbId = projectCodeToDbId[t.projectId]
  if (!projectDbId) {
    console.warn(`[Seed] 跳过任务 ${t.code}: 找不到项目 ${t.projectId}`)
    continue
  }

  const tags = Array.isArray(t.tags) ? JSON.stringify(t.tags) : '[]'

  const result = taskInsert.run({
    projectId: projectDbId,
    code: t.code,
    name: t.name,
    status: t.status,
    assigneeId: t.assigneeId || '',
    assigneeName: t.assigneeName || '待分配',
    startDate: t.plannedStartAt || null,
    dueDate: t.plannedEndAt || null,
    parentId: null,
    nodeLevelType: t.nodeLevelType || 'task',
    priority: t.priority || 'medium',
    progress: t.progress || 0,
    taskType: t.taskType || '标准任务',
    sourceType: t.sourceType || 'manual',
    riskLevel: t.riskLevel || '低风险',
    slaStatus: t.slaStatus || '正常',
    description: null,
    remindCount: t.remindCount || 0,
    tags,
    createdBy: t.createdBy || '系统',
    now,
  })

  const dbId = Number(result.lastInsertRowid)
  frontendIdToDbId[t.id] = dbId
  if (t.parentTaskId) {
    parentMapping.push({ frontendId: t.id, dbId })
  }
  console.log(`[Seed] 任务: ${t.code} (id=${dbId})`)
}

// ── 3. 更新 parentId ──
const parentUpdate = db.prepare('UPDATE project_tasks SET parent_id = @parentId WHERE id = @id')
for (const { frontendId, dbId } of parentMapping) {
  const task = allMockTaskNodes.find(t => t.id === frontendId)
  if (!task?.parentTaskId) continue

  const parentDbId = frontendIdToDbId[task.parentTaskId]
  if (parentDbId) {
    parentUpdate.run({ parentId: parentDbId, id: dbId })
    console.log(`[Seed] 父子关联: ${task.code} -> parentId=${parentDbId}`)
  }
}

db.close()
console.log('[Seed] 完成')
