import type { SupplierItem } from './supplier.types'

export const suppliers: SupplierItem[] = [
  {
    id: 'S1001',
    name: '中建三局集团有限公司',
    code: 'CSCEC-3B-2024',
    category: '施工总承包',
    status: '合作中',
    rating: '4.8',
    ratingIcon: '28.svg',
    contact: '李明',
    city: '武汉市',
    actionIcon: '29.svg',
    currentTaskCount: 5,
    availabilityStatus: 'busy',
    qualificationStatus: '齐全',
    serviceAreas: ['华中', '华东'],
  },
  {
    id: 'S1002',
    name: '远大住宅工业集团股份有限公司',
    code: 'BROAD-MW-2024',
    category: '幕墙工程',
    status: '合作中',
    rating: '4.5',
    ratingIcon: '30.svg',
    contact: '王工',
    city: '长沙市',
    actionIcon: '31.svg',
    currentTaskCount: 3,
    availabilityStatus: 'assignable',
    qualificationStatus: '齐全',
    serviceAreas: ['华中'],
  },
  {
    id: 'S1003',
    name: '华为技术有限公司',
    code: 'HW-TECH-2024',
    category: '智能化系统',
    status: '合作中',
    rating: '4.9',
    ratingIcon: '32.svg',
    contact: '张华',
    city: '深圳市',
    actionIcon: '33.svg',
    currentTaskCount: 2,
    availabilityStatus: 'assignable',
    qualificationStatus: '齐全',
    serviceAreas: ['华南', '华东'],
  },
  {
    id: 'S1004',
    name: '上海宝冶集团有限公司',
    code: 'BY-STEEL-2024',
    category: '钢结构工程',
    status: '合作中',
    rating: '4.2',
    ratingIcon: '34.svg',
    contact: '刘强',
    city: '上海市',
    actionIcon: '35.svg',
    currentTaskCount: 4,
    availabilityStatus: 'busy',
    qualificationStatus: '临期',
    serviceAreas: ['华东'],
  },
  {
    id: 'S1005',
    name: '棕榈生态城镇发展股份有限公司',
    code: 'PALM-LAND-2024',
    category: '园林景观',
    status: '合作中',
    rating: '4.0',
    ratingIcon: '36.svg',
    contact: '陈芳',
    city: '广州市',
    actionIcon: '37.svg',
    currentTaskCount: 1,
    availabilityStatus: 'assignable',
    qualificationStatus: '齐全',
    serviceAreas: ['华南'],
  },
  {
    id: 'S1006',
    name: '天广消防股份有限公司',
    code: 'TG-FIRE-2024',
    category: '消防工程',
    status: '待审核',
    rating: '3.8',
    ratingIcon: '38.svg',
    contact: '周建',
    city: '泉州市',
    actionIcon: '39.svg',
    currentTaskCount: 0,
    availabilityStatus: 'unavailable',
    qualificationStatus: '需补齐',
    serviceAreas: ['华南'],
  },
  {
    id: 'S1007',
    name: '中天建设集团有限公司',
    code: 'ZT-CON-2024',
    category: '施工总承包',
    status: '合作中',
    rating: '4.6',
    ratingIcon: '40.svg',
    contact: '赵磊',
    city: '杭州市',
    actionIcon: '41.svg',
    currentTaskCount: 4,
    availabilityStatus: 'busy',
    qualificationStatus: '齐全',
    serviceAreas: ['华东'],
  },
  {
    id: 'S1008',
    name: '上海恒大材料有限公司',
    code: 'HD-MAT-2024',
    category: '建筑材料',
    status: '已暂停',
    rating: '2.1',
    ratingIcon: '42.svg',
    contact: '孙涛',
    city: '上海市',
    actionIcon: '43.svg',
    currentTaskCount: 0,
    availabilityStatus: 'unavailable',
    qualificationStatus: '临期',
    serviceAreas: ['华东'],
  },
  {
    id: 'S1009',
    name: '杭州天目机电安装有限公司',
    code: 'TM-MEP-2024',
    category: '机电安装',
    status: '合作中',
    rating: '4.3',
    ratingIcon: '44.svg',
    contact: '吴凯',
    city: '杭州市',
    actionIcon: '45.svg',
    currentTaskCount: 2,
    availabilityStatus: 'assignable',
    qualificationStatus: '齐全',
    serviceAreas: ['华东'],
  },
  {
    id: 'S1010',
    name: '南京金陵监理咨询有限公司',
    code: 'JL-CONS-2024',
    category: '工程监理',
    status: '已过期',
    rating: '3.9',
    ratingIcon: '46.svg',
    contact: '郑明',
    city: '南京市',
    actionIcon: '47.svg',
    currentTaskCount: 0,
    availabilityStatus: 'unavailable',
    qualificationStatus: '需补齐',
    serviceAreas: ['华东'],
  },
]
