import type { PersonDetail } from '@/types/personnel'

export const MOCK_PERSON_DETAILS: Record<number, PersonDetail> = {
  1: {
    id: 1,
    personCode: 'P-2026-0001',
    name: '张伟',
    mobile: '138****1234',
    email: 'zhangwei@example.com',
    avatarUrl: null,
    orgId: 1,
    orgName: '华东大区',
    title: '高级项目经理',
    employmentType: 1,
    personStatus: 1,
    availabilityStatus: 1,
    workCity: '上海',
    currentTaskCount: 4,
    criticalTaskCount: 2,
    riskLevel: 1,
    remark: null,
    isDeleted: false,
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-05-06T10:00:00Z',
    avatarOrgName: 'ZW',
    skills: [
      { name: '进度管理', level: '高级' },
      { name: '成本管控', level: '高级' },
      { name: 'BIM', level: '中级' },
    ],
    certs: [
      { name: '一级建造师', certNo: 'JZ-2021-0042', expireAt: '2027-10-18', status: 'valid' },
      { name: 'PMP', certNo: 'PMP-2023-8891', expireAt: '2026-12-30', status: 'valid' },
    ],
    projects: [
      { id: 101, name: '上海南京路旗舰店', role: '项目经理', status: '进行中', progress: '12/18' },
      { id: 102, name: '北京朝阳大悦城店', role: '项目经理', status: '进行中', progress: '3/8' },
      {
        id: 103,
        name: '深圳前海智慧城市试点',
        role: '项目经理',
        status: '已完成',
        progress: '25/25',
      },
    ],
    tasks: [
      {
        title: '审核吊顶施工方案',
        priority: 'P0',
        status: '进行中',
        project: '上海南京路旗舰店',
        due: '2026-03-08',
      },
      {
        title: '编制月度进度汇报',
        priority: 'P1',
        status: '待开始',
        project: '上海南京路旗舰店',
        due: '2026-03-10',
      },
      {
        title: '协调机电施工冲突',
        priority: 'P1',
        status: '进行中',
        project: '北京朝阳大悦城店',
        due: '2026-03-06',
      },
    ],
    statusChanges: [
      {
        type: 'replacement',
        title: '项目二阶段临时替补',
        operator: '系统调度',
        at: '2026-04-08 09:20',
        note: '替补对象：李娜，预计 3 天',
      },
      { type: 'return', title: '请假结束恢复在岗', operator: '人事管理员', at: '2026-03-22 10:15' },
      {
        type: 'leave',
        title: '年假审批通过',
        operator: '直属主管',
        at: '2026-03-15 18:00',
        note: '请假区间：03-18 至 03-21',
      },
    ],
  },
  2: {
    id: 2,
    personCode: 'P-2026-0002',
    name: '李娜',
    mobile: '138****2222',
    email: 'lina@example.com',
    avatarUrl: null,
    orgId: 1,
    orgName: '华东大区',
    title: '项目经理',
    employmentType: 1,
    personStatus: 1,
    availabilityStatus: 2,
    workCity: '苏州',
    currentTaskCount: 5,
    criticalTaskCount: 2,
    riskLevel: 2,
    remark: null,
    isDeleted: false,
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: '2026-05-05T14:00:00Z',
    avatarOrgName: 'LN',
    skills: [
      { name: '合同管理', level: '高级' },
      { name: '沟通协调', level: '中级' },
    ],
    certs: [
      { name: '二级建造师', certNo: 'EJZ-2022-0118', expireAt: '2026-11-18', status: 'valid' },
      { name: '安全员C证', certNo: 'AQ-2024-0320', expireAt: '2026-04-20', status: 'expiring' },
    ],
    projects: [
      { id: 201, name: '苏州园区商业综合体', role: '项目经理', status: '进行中', progress: '8/14' },
      { id: 202, name: '杭州滨江示范店', role: '项目经理', status: '已完成', progress: '7/7' },
    ],
    tasks: [
      {
        title: '确认消防设备进场计划',
        priority: 'P0',
        status: '进行中',
        project: '苏州园区商业综合体',
        due: '2026-04-12',
      },
      {
        title: '输出周报模板',
        priority: 'P1',
        status: '待开始',
        project: '苏州园区商业综合体',
        due: '2026-04-14',
      },
    ],
    statusChanges: [
      {
        type: 'leave',
        title: '调休申请通过',
        operator: '人事管理员',
        at: '2026-04-03 17:30',
        note: '调休半天，已同步项目日程',
      },
      { type: 'return', title: '调休结束恢复在岗', operator: '系统自动', at: '2026-04-04 13:30' },
    ],
  },
  3: {
    id: 3,
    personCode: 'P-2026-0003',
    name: '王强',
    mobile: '138****3333',
    email: 'wangqiang@example.com',
    avatarUrl: null,
    orgId: 1,
    orgName: '华东大区',
    title: '结构负责人',
    employmentType: 1,
    personStatus: 1,
    availabilityStatus: 2,
    workCity: '天津',
    currentTaskCount: 6,
    criticalTaskCount: 3,
    riskLevel: 3,
    remark: null,
    isDeleted: false,
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-05-04T16:00:00Z',
    avatarOrgName: 'WQ',
    skills: [
      { name: '结构设计', level: '高级' },
      { name: '抗震评估', level: '高级' },
      { name: '现场复核', level: '中级' },
    ],
    certs: [
      { name: '一级结构工程师', certNo: 'JG-2020-0031', expireAt: '2028-05-12', status: 'valid' },
      {
        name: '注册监理工程师',
        certNo: 'JL-2022-0087',
        expireAt: '2026-04-15',
        status: 'expiring',
      },
    ],
    projects: [
      { id: 301, name: '天津滨海智慧仓', role: '结构负责人', status: '进行中', progress: '21/26' },
      { id: 302, name: '重庆中庭改造', role: '结构负责人', status: '已完成', progress: '10/10' },
    ],
    tasks: [
      {
        title: '复核支撑体系变更单',
        priority: 'P0',
        status: '阻塞',
        project: '天津滨海智慧仓',
        due: '2026-04-10',
      },
      {
        title: '输出结构校核报告',
        priority: 'P1',
        status: '进行中',
        project: '天津滨海智慧仓',
        due: '2026-04-15',
      },
    ],
    statusChanges: [
      {
        type: 'replacement',
        title: '关键任务替补安排',
        operator: '项目总监',
        at: '2026-04-07 16:00',
        note: '替补对象：周洋（结构组）',
      },
      {
        type: 'leave',
        title: '病假审批通过',
        operator: '人事管理员',
        at: '2026-03-29 09:12',
        note: '时长 2 天',
      },
    ],
  },
  4: {
    id: 4,
    personCode: 'P-2026-0004',
    name: '赵敏',
    mobile: '138****4444',
    email: 'zhaomin@example.com',
    avatarUrl: null,
    orgId: 1,
    orgName: '华东大区',
    title: '质检工程师',
    employmentType: 1,
    personStatus: 2,
    availabilityStatus: 3,
    workCity: '南京',
    currentTaskCount: 2,
    criticalTaskCount: 0,
    riskLevel: 2,
    remark: null,
    isDeleted: false,
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-05-03T09:00:00Z',
    avatarOrgName: 'ZM',
    skills: [
      { name: '质量巡检', level: '中级' },
      { name: '风险排查', level: '中级' },
    ],
    certs: [
      { name: '质量员证', certNo: 'ZLY-2023-0044', expireAt: '2027-01-08', status: 'valid' },
      { name: '高空作业证', certNo: 'GKZ-2024-0021', expireAt: '2026-03-20', status: 'expired' },
    ],
    projects: [
      { id: 401, name: '南京新街口旗舰店', role: '质检工程师', status: '进行中', progress: '5/12' },
    ],
    tasks: [
      {
        title: '材料进场抽检',
        priority: 'P1',
        status: '待开始',
        project: '南京新街口旗舰店',
        due: '2026-04-18',
      },
      {
        title: '施工质量巡检',
        priority: 'P0',
        status: '进行中',
        project: '南京新街口旗舰店',
        due: '2026-04-20',
      },
    ],
    statusChanges: [
      {
        type: 'leave',
        title: '年假审批通过',
        operator: '人事管理员',
        at: '2026-04-01 09:00',
        note: '请假区间：04-02 至 04-05',
      },
      { type: 'return', title: '年假结束恢复在岗', operator: '系统自动', at: '2026-04-06 09:00' },
    ],
  },
  5: {
    id: 5,
    personCode: 'EXT-001',
    name: '吴芳（外部）',
    mobile: '139****7777',
    email: 'wufang@partner.com',
    avatarUrl: null,
    orgId: 1,
    orgName: '华东大区',
    title: '外协负责人',
    employmentType: 3,
    personStatus: 1,
    availabilityStatus: 1,
    workCity: '深圳',
    currentTaskCount: 1,
    criticalTaskCount: 1,
    riskLevel: 3,
    remark: null,
    isDeleted: false,
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-05-06T08:00:00Z',
    avatarOrgName: 'WF',
    skills: [
      { name: '幕墙深化', level: '高级' },
      { name: '现场配合', level: '中级' },
    ],
    certs: [
      { name: '高压电工证', certNo: 'GYD-2024-0099', expireAt: '2026-04-14', status: 'expiring' },
      { name: '特种作业操作证', certNo: 'TZ-2023-0066', expireAt: '2025-12-30', status: 'expired' },
    ],
    projects: [
      { id: 501, name: '深圳万象天地店', role: '幕墙负责人', status: '进行中', progress: '8/14' },
    ],
    tasks: [
      {
        title: '幕墙节点深化设计',
        priority: 'P1',
        status: '进行中',
        project: '深圳万象天地店',
        due: '2026-04-22',
      },
    ],
    statusChanges: [
      {
        type: 'return',
        title: '外协人员入驻',
        operator: '项目经理',
        at: '2026-03-10 14:00',
        note: '远大幕墙委派',
      },
    ],
  },
}

export function getPersonDetail(id: number): PersonDetail | null {
  return MOCK_PERSON_DETAILS[id] ?? null
}
